<!DOCTYPE html>
    <html>
         <head>
             <meta charset="utf-8">
             <meta content="text/html; utf-8" http-equiv="Content-Type" />
             <link rel="stylesheet" type="text/css" href="css/style.css"/>
             <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.js"></script>
             <script type="text/javascript" src="js/utils.js"></script>
             <script src="https://rawgithub.com/digitalBush/jquery.maskedinput/1.3.1/dist/jquery.maskedinput.min.js" type="text/javascript"></script>
            <title>Regplat</title>
         </head>
         <body>
            <div>
            <form action="index.php?action=login" method="post" class="registration">
            <fieldset>

            <legend>Пожалуйста, авторизируйтесь</legend>
            <br/>
            <?php if($this->error): ?>
            <div class="error"><label id="er"><?php echo $this->error ?></label></div><br>
            <?php endif ?>
            <div id="user_text">
                <label>Логин </label>
            </div>
                   <input id="user" type="text" name="username" />
                   <div id="pas_text"><label>Пароль</label></div>
                   <input id = "pas" type="password" name="password" />
                   <input type="hidden" name="try" value="<?php echo $this->try ?>"/>
                <?php if($this->try >= 3): ?>
                <div id="captcha-wrap">
                    <div class="captcha-box">
                        <img src="index.php?module=user&action=getCaptchaImage" alt="" id="captcha" />
                    </div>
                    <div class="text-box">
                        <label>Введите 2 слова:</label>
                        <input name="captcha-code" type="text" id="captcha-code">
                    </div>
                    <div class="captcha-action">
                        <img src="images/refresh.jpg"  alt="" id="captcha-refresh" />
                    </div>
                </div>
                <?php endif; ?>
                   <input type="submit" value="Вход" id="button"/>
                   </fieldset>
               </form>
            </div>

         </body>
    </html>