<!DOCTYPE html>
    <html>
         <head>
             <meta charset="utf-8">
              <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
              <meta http-equiv="refresh" content="600;URL=index.php?update=0">
              <link rel="stylesheet" href="css/demo_page.css" type="text/css" />
              <link rel="stylesheet" href="css/demo_table.css" type="text/css" />
              <link rel="stylesheet" href="css/style.css" type="text/css" />
              <link rel="stylesheet" type="text/css" media="screen" href="css/redmond/jquery-ui-1.10.3.custom.css" />
              <link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />
             <link rel="stylesheet" type="text/css" media="screen" href="css/jquery.ui.timepicker.css" />
             <script type="text/javascript" src="js/jquery-1.10.1.js"></script>
              <script type="text/javascript" src="js/ejs_production.js"></script>
              <script type="text/javascript" src="js/json2.min.js"></script>
              <script type="text/javascript" src="js/utils.js"></script>
              <script type="text/javascript" src="js/help_messages.js"></script>
         <?php if($this->environtment == 'terminal'): ?>
              <script type="text/javascript" src="js/jquery.timeago.js"></script>
              <script type="text/javascript" src="js/jquery.timeago.ru.js"></script>
              <script type="text/javascript" src="js/terminal_test.js"></script>
         <?php elseif($this->environtment == 'provider'): ?>
              <script type="text/javascript" src="js/provider_test.js"></script>
         <?php endif ?>
              <script src="js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
              <script src="js/jquery.ui.timepicker.js" type="text/javascript"></script>
              <script src="js/jquery.ui.datepicker-ru.js" type="text/javascript"></script>
              <script src="js/i18n/grid.locale-ru.js" type="text/javascript"></script>
              <script src="js/jquery.jqGrid.min.js" type="text/javascript"></script>
              <script src="js/plugins/grid.tbltogrid.js" type="text/javascript"></script>
              <script type="text/javascript" src="http://jreject.turnwheel.com/js/jquery.reject.min.js"></script>
              <script src="js/jquery.maskedinput.min.js" type="text/javascript"></script>
              <script type="text/javascript" src="js/jquery.clipboard.js"></script>
              <script src="js/jquery.validate.js"></script>
              <script src="js/additional-methods.js"></script>
              <script type="text/javascript" src="js/profileActions.js"></script>
              <title>regplat</title>
         </head>

         <body id="dt_example">
         <div id='overlay'></div>
         <div id="new_table"></div>
              <div id="container">
                   <div id="header">
                        <a href="/index.php"><img src="images/regplat_small.png" alt="logo"/></a>
                   <?php if($this->environtment == 'terminal'): ?>
                        <h1>Мониторинг терминалов</h1>
                   <?php elseif($this->environtment == 'provider'): ?>
                       <h1>Мониторинг платежей</h1>
                   <?php endif ?>
                   </div>
                   <div class="exit" id="profile"><a class="edit_profile" href="index.php?module=user&action=editProfile" title="Настройки"><img width="30px" src="images/user-icon.png" alt="profile"/></a></div>
                   <div class="exit" id="profile_text"><a class="edit_profile" href="index.php?module=user&action=editProfile" title="Настройки">Настройки</a></div>
                   <div class="exit"><a href="index.php?action=logout" title="Выход"><img src="images/exit.png" alt="exit"/></a></div>
                   <div class="exit" id="exit_text"><a href="index.php?action=logout" title="Выход">Выход</a></div>
                   <div class="exit" id="refresh"><a href="#" title="Обновить"><img src="images/refresh.png" alt="refresh"/></a></div>
                   <div class="exit" id="refresh_text"><a href="index.php" title="Обновить">Обновить</a></div>
