<!DOCTYPE html>
    <html>
         <head>
             <meta charset="utf-8">
              <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
              <meta http-equiv="refresh" content="600">
              <link rel="stylesheet" href="css/demo_page.css" type="text/css" />
              <link rel="stylesheet" href="css/demo_table.css" type="text/css" />
              <link rel="stylesheet" href="css/style.css" type="text/css" />
              <link type="text/css" href="css/ui-lightness/jquery-ui-1.8.22.custom.css" rel="Stylesheet" />
              <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.js"></script>
              <script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
              <script type="text/javascript" src="js/ejs_production.js"></script>
              <script type="text/javascript" src="http://yandex.st/json2/2011-10-19/json2.min.js"></script>
              <script type="text/javascript" src="js/utils.js"></script>
             <script type="text/javascript" src="js/help_messages.js"></script>
         <?php if($this->environtment == 'terminal'): ?>
              <script type="text/javascript" src="js/terminalActions.js"></script>
         <?php elseif($this->environtment == 'provider'): ?>
              <script type="text/javascript" src="js/providerActions.js"></script>
         <?php endif ?>
              <script type="text/javascript" src="js/jquery-ui-1.8.22.custom.min.js"></script>
              <script type="text/javascript" src="http://jreject.turnwheel.com/js/jquery.reject.min.js"></script>
              <script src="https://rawgithub.com/digitalBush/jquery.maskedinput/1.3.1/dist/jquery.maskedinput.min.js" type="text/javascript"></script>
              <title>regplat</title>
         </head>

         <body id="dt_example">
         <div id='overlay'></div>
         <div id="new_table"></div>
              <div id="container">
                   <div id="header">
                        <a href="/index.php"><img src="images/regplat_small.png" alt="logo"/></a>
                   <?php if($this->environtment == 'terminal'): ?>
                        <h1>Мониторинг терминалов</h1>
                   <?php elseif($this->environtment == 'provider'): ?>
                       <h1>Мониторинг платежей</h1>
                   <?php endif ?>
                   </div>
                   <div class="exit" id="profile"><a href="index.php?module=user&action=editProfile" title="Личный кабинет"><img width="30px" src="images/user-icon.png" alt="profile"/></a></div>
                   <div class="exit" id="profile_text"><a href="index.php?module=user&action=editProfile" title="Личный кабинет">Личный кабинет</a></div>
                   <div class="exit"><a href="index.php?action=logout" title="Выход"><img src="images/exit.png" alt="exit"/></a></div>
                   <div class="exit" id="exit_text"><a href="index.php?action=logout" title="Выход">Выход</a></div>
                   <div class="exit" id="refresh"><a href="#" title="Обновить"><img src="images/refresh.png" alt="refresh"/></a></div>
                   <div class="exit" id="refresh_text"><a href="index.php" title="Обновить">Обновить</a></div>
