<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <link rel="stylesheet" href="../web/css/demo_page.css" type="text/css"/>
    <link rel="stylesheet" href="../web/css/demo_table.css" type="text/css"/>
    <link rel="stylesheet" href="../web/css/style.css" type="text/css"/>

    <script type="text/javascript" src="../web/js/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="../web/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../web/js/provider.js"></script>
    <script src="../web/js/jquery.maskedinput.min.js" type="text/javascript"></script>

    <title>regplat</title>
</head>

<body id="dt_example">
<div id="container">
    <div id="header">
        <img src="../web/images/regplat_small.png" alt="logo"/>

        <h1>Мониторинг терминалов</h1>
    </div>
    <div class="exit"><a href="../web/index.php" title="Выход"><img src="../web/images/exit.png" alt="exit"/></a></div>
    <div class="exit" id="exit_text"><a href="../web/index.php" title="Выход">Выход</a></div>
    <div id="agent">
        <h2>Данные агентов</h2>
        <div style="float: right; padding-right: 20px; font-size: 12px;"><img alt="new" src="../web/images/new.png" id="new"/><br>добавить нового агента</div>

        <div class="notvisible" id="right">
            <form action="#" method="post">
                <table>
                    <tr>
                        <td colspan="2">
                            <select id="agent_name" onChange="find_id()">
                                <?php $agent = $this->agent;

                                if (mssql_num_rows($agent) > 0) {
                                    while ($agent_info = library_utils::MyIconv(mssql_fetch_array($agent))) {
                                        echo '<option value="' . $agent_info['provider_oid'] . '">' . $agent_info['ProviderName'] . '</option>';

                                    }
                                } ?>

                            </select>
                            <p style="text-align: left; font-size: 10px">количество провайдеров:<?php echo(mssql_num_rows($agent)); ?></p>
                        </td>
                    </tr>
                    <tr>
                        <td>ID Агента</td>
                        <td><a id="agent_id"></a></td>
                    </tr>
                    <tr>
                        <td>Телефон</td>
                        <td><input type="text" id="agent_phone" name="phone"/></td>
                    </tr>
                    <tr>
                        <td>Пароль</td>
                        <td><input type="text" id="agent_pas" name="password"/></td>
                    </tr>
                    <tr>
                        <td>E-mail</td>
                        <td><input type="text" id="agent_email" name="email"/></td>
                    </tr>
                    <tr>
                        <td>Статус</td>
                        <td><input type="text" id="agent_status" name="status"/></td>
                    </tr>
                    <input type="hidden" name="agentoid" id="agentoid" value=""/>
                    <input type="hidden" name="add" value="1"/>
                </table>
                <input type="submit" value="Сохранить"/></form>
        </div>

        <?php $count = 0; ?>
        <div id="demo_gecko">

            <p style="color: <?php echo $this->color ?>"><?php echo $this->message ?></p>
            <table class="display" id="agent_info">
                <thead>
                    <th>ID Агента</th>
                    <th>Телефон</th>
                    <th>Пароль</th>
                    <th>Email</th>
                    <th>Статус</th>
                    <th></th>
                    <th></th>
                    <th>#</th>
                </thead>
                <tbody>

                <?php    $agent = $this->agent2;

                if (mssql_num_rows($agent) > 0) {
                    while ($agent_info = mssql_fetch_array($agent)) {
                        echo '<tr><td>' . $agent_info['agent_oid'] . '</td><td>' . $agent_info['phone'] . '</td><td>Зашифрованно</td><td>' . $agent_info['email'] . '</td><td>' . $agent_info['status'] . '</td><td><a href="#" class="edit"><img src="../web/images/edit.png"/></a></td><td><a href="#" class="delete"><img src="../web/images/delete.png"/></a></td><td>' . $agent_info['id_login'] . '</td></tr>';
                        $count++;
                    }
                }  ?>
                </tbody>
            </table>

        </div>
    </div>
</div>
</body>
</html>